mybatis-plus:
  mapperLocations: classpath:mapper/**/*.xml
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/object?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    #oss 的配置
#  cloud:
#    alicloud:
#      access-key:
#      secret-key:
#      oss:
#        endpoint:
#        bucket:
  # 设置当前的环境
  profiles:
    active: dev
  jackson:
    default-property-inclusion: non_empty
  redis:
    host: 81.68.139.38
    password: 751026lq
server:
  # 端口
  port: 8889
  #设置项目的访问域名带路径
  servlet:
    context-path: /object
# Sa-Token配置
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: satoken
  # token有效期，单位s 7天, -1代表永不过期
  timeout: 604800
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: tik
  # 是否输出操作日志
  is-log: true
    # 获取参数名为JASYPT的当前系统的环境变量或命令行参数(java -jar xxxx.jar JASYPT=abcd)
    # 使用命令行直接指定盐值 java -jar xxxx.jar --jasypt.encryptor.password=abcd
    # JASYPT作为盐值 JASYPT获取不到时使用abcd作为值
    #  password: #输入你配置密码
jasypt:
  encryptor:
    password: 751026lq


# 实体类生成
entity:
  builder:
    ##   配置是否开启
    open: true
    ## 实体类所在的包
    pack: com.object.test


